doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    schema_filter: "~^(?!doctrine_migration_versions$)~"
    profiling_collect_backtrace: '%kernel.debug%'
    use_savepoints: true
    types:
      # The following are needed, as Doctrine seemingly ignores Carbon when comparing types of properties.
      # When you try to update the schema using bin/console d:s:u, it will recursively try to update them incorrectly.
      datetime_immutable: \Carbon\Doctrine\CarbonImmutableType
      datetime: \Carbon\Doctrine\CarbonType
      carbon_immutable: \Carbon\Doctrine\CarbonImmutableType
      carbon: \Carbon\Doctrine\CarbonType
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    report_fields_where_declared: true
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        type: attribute
        is_bundle: false
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
