# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # --------------------------------------------------------------------------------------------------------------- #
  # Auto-register Services within directories
  # --------------------------------------------------------------------------------------------------------------- #

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\DataManagement\:
    resource: '../src/DataManagement/'
    public: true

  # --------------------------------------------------------------------------------------------------------------- #
  # Command Service Definitions
  # --------------------------------------------------------------------------------------------------------------- #

  App\Command\DataManagement\DataManagementCommand:
    arguments:
      $container: '@service_container'
      $dataManagementFileDirectory: 'src/DataManagement'
      $dataManagementFileNamesToIgnore:
        - 'AbstractDataManagementFile.php'

  # --------------------------------------------------------------------------------------------------------------- #
  # EventListener Service Definitions
  # --------------------------------------------------------------------------------------------------------------- #

  App\EventListener\LoginSubscriber:
    tags:
      - name: kernel.event_subscriber
        dispatcher: security.event_dispatcher.main

  # --------------------------------------------------------------------------------------------------------------- #
  # Factory Service Definitions
  # --------------------------------------------------------------------------------------------------------------- #

  App\Factory\AddressFactory: ~
  App\Factory\AddressFactoryInterface: '@App\Factory\AddressFactory'

  App\Factory\CompanyFactory: ~
  App\Factory\CompanyFactoryInterface: '@App\Factory\CompanyFactory'

  App\Factory\DataManagementLogFactory: ~
  App\Factory\DataManagementLogFactoryInterface: '@App\Factory\DataManagementLogFactory'

  App\Factory\DirectorFactory: ~
  App\Factory\DirectorFactoryInterface: '@App\Factory\DirectorFactory'
  
  App\Factory\ExpenseFactory: ~
  App\Factory\ExpenseFactoryInterface: '@App\Factory\ExpenseFactory'
  
  App\Factory\ExpenseCategoryFactory: ~
  App\Factory\ExpenseCategoryFactoryInterface: '@App\Factory\ExpenseCategoryFactory'

  App\Factory\InvoiceFactory: ~
  App\Factory\InvoiceFactoryInterface: '@App\Factory\InvoiceFactory'

  App\Factory\LanentechFactory: ~
  App\Factory\LanentechFactoryInterface: '@App\Factory\LanentechFactory'

  App\Factory\RepeatCostFactory: ~
  App\Factory\RepeatCostFactoryInterface: '@App\Factory\RepeatCostFactory'
  
  App\Factory\UserFactory: ~
  App\Factory\UserFactoryInterface: '@App\Factory\UserFactory'

  # --------------------------------------------------------------------------------------------------------------- #
  # Repository Service Definitions
  # --------------------------------------------------------------------------------------------------------------- #

  App\Repository\AddressRepository: ~
  App\Repository\AddressRepositoryInterface: '@App\Repository\AddressRepository'

  App\Repository\CompanyRepository: ~
  App\Repository\CompanyRepositoryInterface: '@App\Repository\CompanyRepository'

  App\Repository\DataManagementLogRepository: ~
  App\Repository\DataManagementLogRepositoryInterface: '@App\Repository\DataManagementLogRepository'
  
  App\Repository\DirectorRepository: ~
  App\Repository\DirectorRepositoryInterface: '@App\Repository\DirectorRepository'

  App\Repository\ExpenseRepository: ~
  App\Repository\ExpenseRepositoryInterface: '@App\Repository\ExpenseRepository'
  
  App\Repository\ExpenseCategoryRepository: ~
  App\Repository\ExpenseCategoryRepositoryInterface: '@App\Repository\ExpenseCategoryRepository'

  App\Repository\InvoiceRepository: ~
  App\Repository\InvoiceRepositoryInterface: '@App\Repository\InvoiceRepository'

  App\Repository\LanentechRepository: ~
  App\Repository\LanentechRepositoryInterface: '@App\Repository\LanentechRepository'

  App\Repository\RepeatCostRepository: ~
  App\Repository\RepeatCostRepositoryInterface: '@App\Repository\RepeatCostRepository'

  App\Repository\UserRepository: ~
  App\Repository\UserRepositoryInterface: '@App\Repository\UserRepository'
