# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  # --------------------------------------------------------------------------------------------------------------- #
  # Auto-register Services within directories
  # --------------------------------------------------------------------------------------------------------------- #

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\DataManagement\:
    resource: '../src/DataManagement/'
    public: true

  # --------------------------------------------------------------------------------------------------------------- #
  # Command Service Definitions
  # --------------------------------------------------------------------------------------------------------------- #

  App\Command\DataManagement\DataManagementCommand:
    arguments:
      $container: '@service_container'
      $dataManagementFileDirectory: 'src/DataManagement'
      $dataManagementFileNamesToIgnore:
        - 'AbstractDataManagementFile.php'

  # --------------------------------------------------------------------------------------------------------------- #
  # EventListener Service Definitions
  # --------------------------------------------------------------------------------------------------------------- #

  App\EventListener\LoginSubscriber:
    tags:
      - name: kernel.event_subscriber
        dispatcher: security.event_dispatcher.main

  # --------------------------------------------------------------------------------------------------------------- #
  # Factory Service Definitions
  # --------------------------------------------------------------------------------------------------------------- #

  App\Factory\DataManagementLogFactory: ~
  App\Factory\DataManagementLogFactoryInterface: '@App\Factory\DataManagementLogFactory'
  
  App\Factory\UserFactory: ~
  App\Factory\UserFactoryInterface: '@App\Factory\UserFactory'

  # --------------------------------------------------------------------------------------------------------------- #
  # Repository Service Definitions
  # --------------------------------------------------------------------------------------------------------------- #

  App\Repository\DataManagementLogRepository: ~
  App\Repository\DataManagementLogRepositoryInterface: '@App\Repository\DataManagementLogRepository'

  App\Repository\UserRepository: ~
  App\Repository\UserRepositoryInterface: '@App\Repository\UserRepository'
