services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # --------------------------------------------------------------------------------------------------------------- #
  # DataManagement Service Definitions
  # --------------------------------------------------------------------------------------------------------------- #

  App\Tests\Integration\Command\DataManagement\VersionFiles\ExceptionThrowing\Version20240101010101: ~
  App\Tests\Integration\Command\DataManagement\VersionFiles\MissingExtension\Version20240101010101: ~
  App\Tests\Integration\Command\DataManagement\VersionFiles\Valid\Version20240101010101: ~

  App\Command\DataManagement\DataManagementCommand:
    arguments:
      $container: '@service_container'
      $dataManagementFileDirectory: 'tests/Integration/Command/DataManagement/VersionFiles/Valid/'

  security.csrf.token_manager:
    class: App\Tests\Common\Csrf\CsrfTokenManagerMock

  App\DataManagement\:
    resource: '../src/DataManagement/'
    public: true

  App\Repository\:
    resource: '../src/Repository/'
    public: true
